package com.marks2games.gravitygame.building_game.domain.usecase.newturn

import com.marks2games.gravitygame.building_game.data.model.District
import com.marks2games.gravitygame.building_game.data.model.Planet
import com.marks2games.gravitygame.building_game.data.model.Resource
import com.marks2games.gravitygame.building_game.data.model.UrbanCenterMode
import javax.inject.Inject

/**
 * Use case responsible for calculating the influence growth of a planet.
 *
 * This use case determines the total influence points generated by a planet based on
 * the number of working Urban Center districts that are in "Influence" mode.
 *
 * @constructor Creates an instance of [GenerateInfluenceUseCase].
 */
class GenerateInfluenceUseCase @Inject constructor(){

    /**
     * Invokes the calculation for the total influence generated by a planet's urban centers.
     *
     * This function calculates the sum of influence generated by all urban center districts on a given planet.
     * It filters the planet's districts to include only instances of `District.UrbanCenter` that are currently working
     * and are in the `UrbanCenterMode.INFLUENCE` mode. For each qualifying urban center, it calls
     * `generateResources()` to obtain the resources produced and extracts the amount of `Resource.INFLUENCE`.
     * Finally, it sums up all the influence values from these urban centers to produce the total influence.
     *
     */
    operator fun invoke(planet: Planet): Int {
        return planet.districts
            .filterIsInstance<District.UrbanCenter>()
            .filter { it.isWorking && it.mode == UrbanCenterMode.INFLUENCE }
            .sumOf { it.generateResources().produced[Resource.INFLUENCE] ?: 1 }
    }
}